Develop
0xPolygonHermez/zkevm-rom pull request #401
Opened 2024-09-18 13:42 UTC by ignasirv

Tests

2024-09-18 15:58 UTC, krlosMata requested changes

2024-09-18 15:58 UTC, krlosMata commented on package.json
> +    "@0xpolygonhermez/zkevm-commonjs": "github:0xPolygonHermez/zkevm-commonjs#v8.0.0-rc.1-fork.12",
All those packages references should be a tag with no `rc` versions

2025-05-19 10:50 UTC, laisolizq approved these changes

2025-05-19 20:20 UTC, krlosMata approved these changes
:smile_cat:

2025-05-20 09:10 UTC, laisolizq commented
https://github.com/0xPolygonHermez/zkevm-prover/blob/v9.0.0-RC3/src/main_sm/fork_13/scripts/metadata-rom_13.txt

2025-05-20 09:31 UTC, merged